FROM golang:1.20.5 as builder
WORKDIR /app
RUN go mod init dotto/fc-golang
COPY main.go .
RUN go build -o bin .

FROM golang:1.20.5-alpine
COPY --from=builder /app /app
WORKDIR /app
RUN rm main.go
RUN rm go.mod
ENTRYPOINT [ "/app/bin" ]