FROM golang:1.20.5 as builder
WORKDIR /app
RUN go mod init dotto/fc-golang
COPY main.go .
RUN go build -o bin .
RUN rm main.go
RUN rm go.mod

FROM scratch
COPY --from=builder /app .

ENTRYPOINT ["./bin"]